apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mncissk7y-python 
  janus-idp.io/tekton: mncissk7y-python
  backstage.io/kubernetes-id: mncissk7y-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mncissk7y-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml